node {
    def server = Artifactory.server('killabayteyarick.jfrog.io')
    def rtGradle = Artifactory.newGradleBuild()
    def buildInfo = Artifactory.newBuildInfo()
    stage 'Build'
        git url: 'https://github.com/killabayte/gs-gradle.git'

    stage 'ArtifactoryConfiguration'
        rtGradle.tool = 'gradle' // Tool name from Jenkins configuration
        rtGradle.deployer repo:'gradle-dev-local',  server: server
        rtGradle.resolver repo:'gradle-dev', server: server

        stage('ConfigBuildInfo') {
            buildInfo.env.capture = true
            buildInfo.env.filter.addInclude("*")
        }

        stage('ExtraGradleConfigurations') {
            rtGradle.usesPlugin = true // Artifactory plugin already defined in build script
        }
        stage('ExecGradle') {
            rtGradle.run rootDir: "artifactory/", buildFile: 'build.gradle', tasks: 'clean artifactoryPublish', buildInfo: buildInfo
        }
        stage('PublishBuildInfo') {
            server.publishBuildInfo buildInfo
        }
}
