Vagrant.configure(2) do |config|
    config.vm.define "builder" do |builder|
        builder.vm.box = "ubuntu/xenial64"
        builder.vm.provision "shell", path: "scripts/install.sh"
        builder.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
        end
    config.vm.network :forwarded_port, guest: 2244, host: 2244
    end
end
